package dev.kotforge.kapability.processor

import java.io.File

/**
 * Emits the iOS Swift glue as plain source (Xcode compiles it — Kotlin/Native cannot produce
 * discoverable App Intents). Swift structs are trivial, so this is a small string emitter rather
 * than a codegen library. Strings-only type mapping, matching M1/M2 scope.
 */
internal object SwiftEmitter {

    fun emit(allCaps: List<CapabilityModel>, outDir: File) {
        outDir.mkdirs()
        val caps = allCaps.filter { "IOS" in it.platforms }
        caps.mapNotNull { it.entity }.distinctBy { it.className.simpleName }.forEach { entity ->
            File(outDir, "${entityName(entity)}.swift").writeText(entitySwift(entity))
        }
        caps.forEach { cap ->
            File(outDir, "${intentName(cap)}.swift").writeText(intentSwift(cap))
        }
    }

    private fun entityName(entity: EntityModel): String = "${entity.className.simpleName}Entity"

    private fun intentName(cap: CapabilityModel): String =
        "${cap.functionName.replaceFirstChar { it.uppercase() }}Intent"

    private fun entitySwift(entity: EntityModel): String {
        val name = entityName(entity)
        val props = entity.properties
        val displayProp = (props.firstOrNull { it.name != entity.idProperty } ?: props.firstOrNull())?.name ?: "id"

        val letDecls = props.joinToString("\n") { "    let ${it.name}: ${scalarOf(it.type)!!.swiftType()}" }
        val fromInit = props.joinToString("\n") { "        self.${it.name} = ${scalarOf(it.type)!!.swiftDecode(it.name)}" }

        return buildString {
            appendLine("// Generated by Kapability. Do not edit.")
            appendLine("import AppIntents")
            appendLine()
            appendLine("struct $name: AppEntity {")
            appendLine(letDecls)
            appendLine()
            appendLine("    init(from map: [String: String]) {")
            appendLine(fromInit)
            appendLine("    }")
            appendLine()
            appendLine("    static var typeDisplayRepresentation: TypeDisplayRepresentation { \"${entity.className.simpleName}\" }")
            appendLine("    var displayRepresentation: DisplayRepresentation { DisplayRepresentation(title: \"\\($displayProp)\") }")
            appendLine()
            appendLine("    static let defaultQuery = ${name}Query()")
            appendLine("}")
            appendLine()
            appendLine("struct ${name}Query: EntityQuery {")
            appendLine("    func entities(for identifiers: [String]) async throws -> [$name] { [] }")
            appendLine("    func suggestedEntities() async throws -> [$name] { [] }")
            appendLine("}")
        }
    }

    private fun intentSwift(cap: CapabilityModel): String {
        val entity = cap.entity
            ?: error("M2 supports only @CapabilityEntity return types: ${cap.functionName}")
        val name = intentName(cap)
        val entityStruct = entityName(entity)

        val params = cap.params.joinToString("\n") { p ->
            "    @Parameter(title: \"${swiftEscape(p.description.ifBlank { p.name })}\") var ${p.name}: ${scalarOf(p.type)!!.swiftType()}"
        }
        val invokeParams = cap.params.joinToString(", ") { "\"${it.name}\": ${scalarOf(it.type)!!.swiftEncode(it.name)}" }

        return buildString {
            appendLine("// Generated by Kapability. Do not edit.")
            appendLine("import AppIntents")
            appendLine("import Shared")
            appendLine()
            appendLine("struct $name: AppIntent {")
            appendLine("    static let title: LocalizedStringResource = \"${swiftEscape(camelToTitle(cap.functionName))}\"")
            appendLine("    static let description = IntentDescription(\"${swiftEscape(cap.description)}\")")
            appendLine()
            appendLine(params)
            appendLine()
            appendLine("    init() {}")
            appendLine()
            appendLine("    func perform() async throws -> some IntentResult & ReturnsValue<$entityStruct> {")
            appendLine("        let result = try await KapabilityRuntime.shared.invoke(")
            appendLine("            id: \"${cap.id}\",")
            appendLine("            params: [$invokeParams]")
            appendLine("        )")
            appendLine("        return .result(value: $entityStruct(from: result))")
            appendLine("    }")
            appendLine("}")
        }
    }

    private fun camelToTitle(s: String): String =
        s.replaceFirstChar { it.uppercase() }.replace(Regex("([a-z])([A-Z])"), "$1 $2")

    private fun swiftEscape(s: String): String = s.replace("\\", "\\\\").replace("\"", "\\\"")
}
