package dev.kotforge.kapability.processor

import java.io.File

/**
 * Emits the iOS Swift glue as plain source (Xcode compiles it — Kotlin/Native cannot produce
 * discoverable App Intents). The bridge is a JSON document string: params are built into a
 * `[String: Any]` dict and serialized with `JSONSerialization`; the result JSON is parsed back the
 * same way. Enums used in params/entities are emitted as `AppEnum` conformances.
 */
internal object SwiftEmitter {

    fun emit(allCaps: List<CapabilityModel>, outDir: File) {
        outDir.mkdirs()
        val caps = allCaps.filter { "IOS" in it.platforms }

        // Shared JSON bridge helper.
        File(outDir, "KapabilityBridge.swift").writeText(supportSwift())

        // One AppEnum file per distinct enum used across params + entity properties.
        val enums = caps.flatMap { cap ->
            cap.params.mapNotNull { enumOf(it.supported) } +
                (cap.entity?.properties?.mapNotNull { enumOf(it.supported) } ?: emptyList())
        }.distinctBy { it.className.simpleName }
        enums.forEach { File(outDir, "${it.className.simpleName}.swift").writeText(enumSwift(it)) }

        caps.mapNotNull { it.entity }.distinctBy { it.className.simpleName }.forEach { entity ->
            File(outDir, "${entityName(entity)}.swift").writeText(entitySwift(entity))
        }
        caps.forEach { cap ->
            File(outDir, "${intentName(cap)}.swift").writeText(intentSwift(cap))
        }
    }

    /** The enum type behind a value (unwrapping nullable), or null if the type is not an enum. */
    private fun enumOf(t: SupportedType?): SupportedType.EnumType? = when (t) {
        is SupportedType.EnumType -> t
        is SupportedType.NullableType -> t.inner as? SupportedType.EnumType
        else -> null
    }

    private fun entityName(entity: EntityModel): String = "${entity.className.simpleName}Entity"

    private fun intentName(cap: CapabilityModel): String =
        "${cap.functionName.replaceFirstChar { it.uppercase() }}Intent"

    private fun supportSwift(): String = buildString {
        appendLine("// Generated by Kapability. Do not edit.")
        appendLine("import Foundation")
        appendLine()
        appendLine("enum KapabilityBridge {")
        appendLine("    static func encode(_ obj: [String: Any]) -> String {")
        appendLine("        guard let data = try? JSONSerialization.data(withJSONObject: obj),")
        appendLine("              let json = String(data: data, encoding: .utf8) else { return \"{}\" }")
        appendLine("        return json")
        appendLine("    }")
        appendLine()
        appendLine("    static func decode(_ json: String) -> [String: Any] {")
        appendLine("        guard let data = json.data(using: .utf8),")
        appendLine("              let obj = try? JSONSerialization.jsonObject(with: data),")
        appendLine("              let dict = obj as? [String: Any] else { return [:] }")
        appendLine("        return dict")
        appendLine("    }")
        appendLine("}")
    }

    private fun enumSwift(e: SupportedType.EnumType): String {
        val name = e.className.simpleName
        val cases = e.caseNames.joinToString("\n") { "    case $it" }
        val displays = e.caseNames.joinToString("\n") { "            .$it: \"${swiftEscape(it)}\"," }
        return buildString {
            appendLine("// Generated by Kapability. Do not edit.")
            appendLine("import AppIntents")
            appendLine()
            // `: String` raw values equal the case names, matching the Kotlin enum's `.name` on the wire.
            appendLine("enum $name: String, AppEnum {")
            appendLine(cases)
            appendLine()
            appendLine("    static var typeDisplayRepresentation: TypeDisplayRepresentation { \"$name\" }")
            appendLine("    static var caseDisplayRepresentations: [$name: DisplayRepresentation] {")
            appendLine("        [")
            appendLine(displays)
            appendLine("        ]")
            appendLine("    }")
            appendLine("}")
        }
    }

    private fun entitySwift(entity: EntityModel): String {
        val name = entityName(entity)
        val props = entity.properties
        val displayProp = (props.firstOrNull { it.name != entity.idProperty } ?: props.firstOrNull())?.name ?: "id"

        val letDecls = props.joinToString("\n") { "    let ${it.name}: ${it.supported!!.swiftType()}" }
        val fromInit = props.joinToString("\n") { "        self.${it.name} = ${it.supported!!.swiftDecode("dict", it.name)}" }

        return buildString {
            appendLine("// Generated by Kapability. Do not edit.")
            appendLine("import AppIntents")
            appendLine("import Foundation")
            appendLine()
            appendLine("struct $name: AppEntity {")
            appendLine(letDecls)
            appendLine()
            appendLine("    init(from dict: [String: Any]) {")
            appendLine(fromInit)
            appendLine("    }")
            appendLine()
            appendLine("    static var typeDisplayRepresentation: TypeDisplayRepresentation { \"${entity.className.simpleName}\" }")
            appendLine("    var displayRepresentation: DisplayRepresentation { DisplayRepresentation(title: \"\\($displayProp)\") }")
            appendLine()
            appendLine("    static let defaultQuery = ${name}Query()")
            appendLine("}")
            appendLine()
            appendLine("struct ${name}Query: EntityQuery {")
            appendLine("    func entities(for identifiers: [String]) async throws -> [$name] { [] }")
            appendLine("    func suggestedEntities() async throws -> [$name] { [] }")
            appendLine("}")
        }
    }

    private fun intentSwift(cap: CapabilityModel): String {
        val entity = cap.entity
            ?: error("Kapability supports only @CapabilityEntity return types: ${cap.functionName}")
        val name = intentName(cap)
        val entityStruct = entityName(entity)

        val paramDecls = cap.params.joinToString("\n") { p ->
            "    @Parameter(title: \"${swiftEscape(p.description.ifBlank { p.name })}\") var ${p.name}: ${p.supported!!.swiftType()}"
        }
        val putLines = cap.params.joinToString("\n") { p ->
            "        params[\"${p.name}\"] = ${p.supported!!.swiftEncode(p.name)}"
        }

        return buildString {
            appendLine("// Generated by Kapability. Do not edit.")
            appendLine("import AppIntents")
            appendLine("import Foundation")
            appendLine("import Shared")
            appendLine()
            appendLine("struct $name: AppIntent {")
            appendLine("    static let title: LocalizedStringResource = \"${swiftEscape(camelToTitle(cap.functionName))}\"")
            appendLine("    static let description = IntentDescription(\"${swiftEscape(cap.description)}\")")
            appendLine()
            if (cap.params.isNotEmpty()) {
                appendLine(paramDecls)
                appendLine()
            }
            appendLine("    init() {}")
            appendLine()
            appendLine("    func perform() async throws -> some IntentResult & ReturnsValue<$entityStruct> {")
            appendLine("        var params: [String: Any] = [:]")
            if (cap.params.isNotEmpty()) appendLine(putLines)
            appendLine("        let resultJSON = try await KapabilityRuntime.shared.invoke(")
            appendLine("            id: \"${cap.id}\",")
            appendLine("            params: KapabilityBridge.encode(params)")
            appendLine("        )")
            appendLine("        let dict = KapabilityBridge.decode(resultJSON)")
            appendLine("        return .result(value: $entityStruct(from: dict))")
            appendLine("    }")
            appendLine("}")
        }
    }

    private fun camelToTitle(s: String): String =
        s.replaceFirstChar { it.uppercase() }.replace(Regex("([a-z])([A-Z])"), "$1 $2")

    private fun swiftEscape(s: String): String = s.replace("\\", "\\\\").replace("\"", "\\\"")
}
